server.port=8080
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
jwt.secret=cooperativeOlivesSecretKey2026ForJWTTokenGeneration1234567890
jwt.expiration=864000000
logging.level.com.example.demo=DEBUG
spring.data.mongodb.uri=mongodb+srv://zitouna:zitouna123@cluster0.4o8wguh.mongodb.net/
spring.data.mongodb.database=cooperative_olives
# Gmail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cooperativedolivesfax@gmail.com
spring.mail.password=lfrk escw zhqr tqeq 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.data.mongodb.auto-index-creation=true